#!/bin/sh
#
# Part of Xigmanas® (https://www.xigmanas.com).
# Copyright © 2018-2020 XigmaNAS® <info@xigmanas.com>.
# All rights reserved.
#

# PROVIDE: CONFIG
# REQUIRE: SYSTEMINIT
# BEFORE: NETWORKING NETWORK

#	This is a dummy dependency.
