#!/bin/sh
#
# Part of XigmaNAS (http://www.xigmanas.com).
# Copyright (c) 2018 XigmaNAS <info@xigmanas.com>.
# All rights reserved.
#

# PROVIDE: DAEMON
# REQUIRE: NETWORKING SERVERS CONFIG

#	This is a dummy dependency, to ensure that general purpose daemons
#	are run _after_ the above are.
