#!/bin/sh
#
# Part of XigmaNAS (https://www.xigmanas.com).
# Copyright © 2018-2020 XigmaNAS®<info@xigmanas.com>.
# All rights reserved.
#
# This script export users to Quixplorer config.
#

# PROVIDE: fmperm
# REQUIRE: DAEMON

. /etc/rc.subr
. /etc/configxml.subr

name="fmperm"
desc="export users to Quixplorer config"
load_rc_config "$name"

#	defaults
fmperm_configdir=${fmperm_configdir:-"/usr/local/www/quixplorer/_config"}
fmperm_htusers=${fmperm_htusers:-"${fmperm_configdir}/.htusers.php"}
fmperm_user_permissions=${fmperm_user_permissions:-"17"}
fmperm_user_active=${fmperm_user_active:-"1"}

echo "Preparing web-based file-management."

#	generate .htusers.php file and export user accounts
echo '<?php' > ${fmperm_htusers}
echo "//	created by $name" >> ${fmperm_htusers}
echo '$GLOBALS["users"] = [];' >> ${fmperm_htusers}

#	option to disable/enable 'File Manager' by WebGUI
if [ `configxml_get_count "//system/disablefm"` -eq 0 ]; then
#	process configured users
	/usr/local/bin/xml sel --template \
		--match '//access/user[enable]' \
			--output '$GLOBALS["users"][] = [' \
			--output "'" \
			--value-of 'login' \
			--output "','" \
			--value-of 'passwordsha' \
			--output "','" \
			--if 'string-length(homedir) > 0' \
				--value-of 'homedir' \
			--else \
				--output '/mnt' \
			--break \
			--output "','http://localhost',0,'^.ht',${fmperm_user_permissions},${fmperm_user_active}" \
			--output '];' \
			--nl \
		--break \
		${configxml_file} | /usr/local/bin/xml unesc >> ${fmperm_htusers}

#	process administrator and root user
	/usr/local/bin/xml sel --template \
		--output '$GLOBALS["users"][] = [' \
		--output "'" \
		--value-of '//system/username' \
		--output "','" \
		--value-of '//system/password' \
		--output "','/','http://localhost',1,'',32847,1" \
		--output '];' \
		--nl \
		--output '$GLOBALS["users"][] = [' \
		--output "'"  \
		--output 'root' \
		--output "','" \
		--value-of '//system/password' \
		--output "','/','http://localhost',1,'',32847,1" \
		--output '];' \
		--nl \
		${configxml_file} | /usr/local/bin/xml unesc >> ${fmperm_htusers}
fi
