#!/bin/sh
#
# Part of XigmaNAS® (https://www.xigmanas.com).
# Copyright © 2018-2021 XigmaNAS® <info@xigmanas.com>.
# All rights reserved.
#
# $FreeBSD: libexec/rc/rc.d/routing/root
# Changes: Remove original code from root_start.
#

# PROVIDE: root
# REQUIRE: fsck
# KEYWORD: nojail

. /etc/rc.subr

name="root"
start_cmd="root_start"
stop_cmd=":"

root_start()
{
	# Currently this script is used as dummy.
}

load_rc_config $name
run_rc_command "$1"
