#!/bin/sh
#
# Part of XigmaNAS® (https://www.xigmanas.com).
# Copyright © 2018-2021 XigmaNAS® <info@xigmanas.com>.
# All rights reserved.
#

# PROVIDE: SERVERS
# REQUIRE: mountcritremote

#	This is a dummy dependency, for early-start servers relying on
#	some basic configuration.
