#!/bin/sh
#
# Part of XigmaNAS (http://www.xigmanas.com).
# Copyright (c) 2018 The XigmaNAS Project <info@xigmanas.com>.
# All rights reserved.
#

# PROVIDE: SYSTEMINIT

#	This is a dummy dependency.
