#!/bin/sh
#
# Part of XigmaNAS (https://www.xigmanas.com).
# Copyright (c) 2018-2019 XigmaNAS <info@xigmanas.com>.
# All rights reserved.
#
# Configure htpasswd
#

# PROVIDE: websrv_htpasswd
# REQUIRE: userdb DAEMON
# XQUERY: --if 'count(//websrv/enable) > 0 and count(//websrv/authentication) > 0' --output '0' --break
# RCVAR: websrv_htpasswd

. /etc/rc.subr
. /etc/configxml.subr

if configxml_isset //websrv/enable; then
	if configxml_isset //websrv/authentication; then
#		defaults
		documentroot=`configxml_get "//websrv/documentroot"`
		htpasswdfile=".websrv_htpasswd"
		htpasswd="${documentroot}/${htpasswdfile}"
		echo "Generating ${htpasswdfile}."
#		generate the htpasswd file used by websrv.
		/bin/cat /dev/null > "${htpasswd}"
#		add configured users.
		/usr/local/bin/xml sel --template \
			--match "//access/user[not(inactive)]" \
				--if 'string-length(login) > 0' \
					--if 'string-length(passwordsha) > 0' \
						--value-of 'concat(login,":",passwordsha)' --nl \
					--else \
						--value-of 'concat(login,":*")' --nl \
					--break \
				--break \
			--break \
			${configxml_file} | /usr/local/bin/xml unesc >> "${htpasswd}"
		/bin/chmod 0600 "${htpasswd}"
		/usr/sbin/chown www:www "${htpasswd}"
	fi
fi
