etc/inc/XMLRPC
etc/rc.beupgrade
usr/local/etc/php/ext-20-intl.ini
usr/local/lib/samba/libldb.so.1
usr/local/www/diag_infos.php
usr/local/www/diag_infos_ata.php
usr/local/www/diag_infos_disksinfo.php
usr/local/www/graph.php
usr/local/www/graph_cpu.php
usr/local/www/status_report.php
usr/local/www/system_rrdgraphs.php
usr/local/www/xmlrpc.php
usr/local/www/images/navbar_active.png
usr/local/www/images/navbar_default.png
etc/install/include/boot/menu.4th
etc/install/include/boot
# 6536
etc/inc/properties_services_ctl.php
etc/inc/properties_services_ctl_auth_group.php
etc/inc/properties_services_ctl_lun.php
etc/inc/properties_services_ctl_portal_group.php
etc/inc/properties_services_ctl_sub_chap.php
etc/inc/properties_services_ctl_sub_chap_mutual.php
etc/inc/properties_services_ctl_sub_initiator_name.php
etc/inc/properties_services_ctl_sub_initiator_portal.php
etc/inc/properties_services_ctl_sub_isnsserver.php
etc/inc/properties_services_ctl_sub_listen.php
etc/inc/properties_services_ctl_sub_lun.php
etc/inc/properties_services_ctl_sub_option.php
etc/inc/properties_services_ctl_sub_port.php
etc/inc/properties_services_ctl_target.php
etc/inc/properties_services_mariadb.php
etc/inc/properties_syslogconf.php
# 6570
etc/inc/properties_smartmontoold_umass.php
# 6575
etc/inc/properties_iscsi_initiator.php
# 6601
etc/inc/properties_services_tftp.php
# 6632
usr/local/www/services_nfs_share.php
usr/local/www/services_nfs_share_edit.php
# 6651
etc/inc/properties_access_users.php
# 6767
usr/local/libexec/in.tftpd
# 6942
etc/inc/properties_services_samba_share.php
etc/inc/properties_services_samba_share_edit.php
# 7010
etc/inc/properties_sysctl.php
