#!/usr/local/bin/php-cgi -f
<?php
#
# Part of XigmaNAS (http://www.xigmanas.com).
# Copyright (c) 2018 The XigmaNAS Project <info@xigmanas.com>.
# All rights reserved.
#
require_once 'report.inc';

$retval = @report_send_mail();
exit($retval);
?>
